### ISSUE TITLE
Add FantaCat#8387 [build]

### ISSUE THREAD

**Issue by FantaCaat** [Discord-Custom-Gradient-Names/gradient#111]
{
 "color1": "#ff4242",
 "color2": "#ff8080",
 "userID": "325934332290007042",
 "username": "FantaCat#8387",
 "angle": "45deg"
}

**Comment by AAGaming00** [comment]
the github action seems to have broken, I'll fix to in a bit

**Comment by FantaCaat** [comment]
> the github action seems to have broken, I'll fix to in a bit

Thanks a lot pal.

**Comment by AAGaming00** [comment]
sorry for the late response, it's fixed
